ygg-database-config:
  database: ${YGG_DATABASE_NAME}
  database_extension: ${YGG_DATABASE_EXTENSION}
  database_location: ${YGG_DATABASE_LOCATION}
  environment: ${YGG_DATABASE_ENVIRONMENT}
  data_location: ${YGG_DATA_LOCATION}

ygg-metadata-catalog-database-config:
  database: ${YGG_CATALOG_DATABASE_NAME}
  database_extension: ${YGG_CATALOG_DATABASE_EXTENSION}
  database_location: ${YGG_CATALOG_DATABASE_LOCATION}
  environment: ${YGG_CATALOG_DATABASE_ENVIRONMENT}

ygg-sink-config:
  location: ${YGG_SINK_LOCATION}

ygg-repository-config:
  repository: ${YGG_REPOSITORY_NAME}
  ducklake_repository: ${YGG_DUCKLAKE_REPOSITORY}
  ducklake_metadata_repository: ${YGG_DUCKLAKE_METADATA_REPOSITORY}
  ducklake_repository_data_location: ${YGG_DUCKLAKE_REPOSITORY_DATA_LOCATION}

ygg-s3-config:
  endpoint_url: ${YGG_S3_CONFIG_ENDPOINT_URL}
  aws_access_key_id: ${YGG_S3_AWS_ACCESS_KEY_ID}
  aws_secret_access_key: ${YGG_S3_AWS_SECRET_ACCESS_KEY}
  region_name: ${YGG_S3_REGION_NAME}
