snowflake:
  sf_snowflake_organization_usage:
    account: ${ACCOUNT}
    user: ${USER}
    auth_type: ${AUTH_TYPE}
    password: ${PASSWORD}
    authenticator: ${AUTHENTICATOR}
    private_key_file: ${PRIVATE_KEY_FILE}
    private_key_password: ${PRIVATE_KEY_PASSWORD}
    role: ${ROLE}
    warehouse: ${WAREHOUSE}
    read_only: ${READ_ONLY}

duckdb:
  ddb_snowflake_organization_usage:
    file_path: /Users/thiagodias/Tad/projects/tyr/ygg/dev/data/file.duckdb

  ddb_snowflake_organization_usage_analytics:
    file_path: /Users/thiagodias/Tad/projects/tyr/ygg/dev/data/file.duckdb
